# -*- coding: utf-8 -*-
"""WebPageGenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7CKXlgr4BK0do9DEYJfT94f3p7vnnw4
"""

'''Auto-Generate a web page'''
import webbrowser
import os

def generate_html(filename, name, description, extension='html')->str:
  html_string = ""
  html_string += f'''<html>
  <head></head>
  <body>
    <center>
      <h1>{name}</h1>
    </center>
    <hr />
    <p>{description}</p>
    <hr />
  </body>
  </html>'''

  outfile = open(f'{filename}.{extension}', 'w')
  outfile.write(html_string)
  outfile.close()
  return html_string

def main():
  name = input("Enter your name: ")
  description = input("Describe yourself: ")
  filename = f'{name}'
  html_string = generate_html(filename, name, description)
  print(f'HTML source code: \n{html_string}')

  current_dir = os.getcwd()
  filepath = os.path.join(current_dir, f'{filename}.html')
  webbrowser.open(f'file://{filepath}')
if __name__ == '__main__':
  main()
